[package]
name = "github-profile"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
inquire = "0.3.0"
reqwest = "0.11.11"
serde = {version="1.0.144", features=["derive"]}
serde_json = "1.0.85"
thiserror = "1.0.34"
tokio = { version = "1.21.0", features = ["full"] }
